services:
  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile.pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./pb/data:/pb/pb_data
      - ./pb/public:/pb/pb_public
      - ./pb/hooks:/pb/pb_hooks
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
